services:
  payment:
    build:
      context: ./esd_payment
      dockerfile: Dockerfile
    restart: always
    environment:
      webServerURL: "http://localhost:5173"
    ports:
      - 3010:5000

  recommendation:
    build:
      context: ./esd_recommend
      dockerfile: Dockerfile
    environment:
      # to change
      externalService: "172.28.110.113" #  declaration using - externalService didn't work, so changed to this. 
    restart: always
    ports:
      - 3008:5000

  review:
    build:
      context: ./esd_review
      dockerfile: Dockerfile
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/review
    ports:
      - 3002:5000