services:

  complex_brand_view_cc:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      internalService: "192.168.192.146"

    ports:
      - 3009:5100