services:
  payment:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      STRIPE_PRIVATE_KEY: sk_test_51OuGi52KwIS1b45LvlM5Q8z0AaTmdNohKDWk3pOEKhNbvOmHJmCEU9DWbSab871Yal3Qw5H2QMXDynjOuQC6NLXB00NBUhtZne
      CLIENT_URL: "123"
    ports:
      - 3010:5000