services:
  blacklist:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/blacklist
    ports:
      - 3005:5000