
networks:
  kafka-net:
    driver: bridge
    name: kafka-net


services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    networks:
      - kafka-net


  kafka:
    restart: always
    image: confluentinc/cp-kafka
    hostname: kafka
    networks:
      - kafka-net
    ports:
      - 9092:9092
    environment:

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 

    depends_on:
      - zookeeper


  notification:
    restart: always
    hostname: notification
    environment:
      mailgunDomain: sandbox3830718b42d748999166ceb664223250.mailgun.org
      mailgunAPIKeyID: 4c205c86-023f941d
      mailgunAPIKey: 1d656920fa2a6e77f0bc70d7ec94b3b8-4c205c86-023f941d
      
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - kafka-net
    ports:
      - 3006:3000



  