version: "3.8"
networks:
  kafka-net:
    driver: bridge
    name: kafka-net
services:

  #################################
  # Account: The Account microservice
  #################################
  account:
    build:
      context: ./esd_account
      dockerfile: Dockerfile
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/account

    ports:
      - 3000:5000
      
  #################################
  # Blacklist: The Blacklist microservice
  #################################
  blacklist:
    build:
      context: ./esd_blacklist
      dockerfile: Dockerfile
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/blacklist
    ports:
      - 3005:5000

  #################################
  # Collaboration: The Collaboration microservice
  #################################
  collaboration:
    build:
      context: ./esd_collab
      dockerfile: Dockerfile
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/collaboration
    ports:
      - 3001:5000
  
  #################################
  # Notification: The Notification microservice
  #################################



  zookeeper:
    image: zookeeper
    hostname: zookeeper
    networks:
      - kafka-net


  kafka:
    restart: always
    image: confluentinc/cp-kafka
    hostname: kafka
    networks:
      - kafka-net
    ports:
      - 9092:9092
    environment:

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 

    depends_on:
      - zookeeper


  notification:
    restart: always
    hostname: notification
    environment:
      mailgunDomain: sandbox5314bb250fea415fbc2913ee0060a1f5.mailgun.org
      mailgunAPIKeyID: b02bcf9f-d6c98002
      mailgunAPIKey: 05bc8f30070e21bc684a40c3e143e144-b02bcf9f-d6c98002
    build:
      context: ./esd_kafka
      dockerfile: Dockerfile
    networks:
      - kafka-net
    ports:
      - 3006:3000
  #################################
  # Payment: The Payment microservice
  #################################

  payment:
    build:
      context: ./esd_payment
      dockerfile: Dockerfile
    restart: always
    environment:
      STRIPE_PRIVATE_KEY: sk_test_51OuGi52KwIS1b45LvlM5Q8z0AaTmdNohKDWk3pOEKhNbvOmHJmCEU9DWbSab871Yal3Qw5H2QMXDynjOuQC6NLXB00NBUhtZne
      CLIENT_URL: "123"
    ports:
      - 3010:5000

  #################################
  # Project: The Project microservice
  #################################

  project:
    build:
      context: ./esd_project
      dockerfile: Dockerfile
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/project
    ports:
      - 3003:5000
  #################################
  # Recommendation: The Recommendation microservice
  #################################
  recommendation:
    build:
      context: ./esd_recommend
      dockerfile: Dockerfile
    environment:
      simpleServer: "172.28.110.113"
    restart: always
    ports:
      - 3008:5000

  #################################
  # Review: The Review microservice
  #################################
  review:
    build:
      context: ./esd_review
      dockerfile: Dockerfile
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/review
    ports:
      - 3002:5000