services:
  account:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/account
    ports:
      - 3000:5000