services:
  complex_view_cc_profile:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      internalService: "192.168.192.146"
    ports:
      - 3004:5100