networks:
  kafka-net:
    driver: bridge
    name: kafka-net

services:
  account:
    build:
      context: ./esd_account
      dockerfile: Dockerfile
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/account
    ports:
      - 3000:5000

  collaboration:
    build:
      context: ./esd_collab
      dockerfile: Dockerfile
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/collaboration
    ports:
      - 3001:5000


  project:
    build:
      context: ./esd_project
      dockerfile: Dockerfile
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/project
    ports:
      - 3003:5000




  complex_view_cc_profile:
    build:
      context: ./esd_complex_view_cc_profile
      dockerfile: Dockerfile
    restart: always
    environment:
    # to change
      internalService: "172.28.110.113"
    ports:
      - 3004:5100

  blacklist:
    build:
      context: ./esd_blacklist
      dockerfile: Dockerfile
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/blacklist
    ports:
      - 3005:5000
  
  complex_place_request:
    build:
      context: ./esd_complex_place_request
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3007:5100  



  complex_brand_view_cc:
    build:
      context: ./esd_complex_brand_view_profile
      dockerfile: Dockerfile
    restart: always
    environment:
    # to change
      internalService: "172.28.110.113"

    ports:
      - 3009:5100

  complex_update_request:
    build:
      context: ./esd_complex_update_collab
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3011:5100



  complex_brand_close_collab:
    build:
      context: ./esd_complex_brand_close_collab
      dockerfile: Dockerfile
    restart: always
    environment:
    # to change
      internalService: "172.28.110.113"
    ports:
      - 3012:5100














  zookeeper:
    image: zookeeper
    hostname: zookeeper
    networks:
      - kafka-net


  kafka:
    restart: always
    image: confluentinc/cp-kafka
    hostname: kafka
    networks:
      - kafka-net
    ports:
      - 9092:9092
    environment:

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 

    depends_on:
      - zookeeper


  notification:
    restart: always
    hostname: notification
    environment:
      mailgunDomain: sandbox3830718b42d748999166ceb664223250.mailgun.org
      mailgunAPIKeyID: 4c205c86-023f941d
      mailgunAPIKey: 1d656920fa2a6e77f0bc70d7ec94b3b8-4c205c86-023f941d
    build:
      context: ./esd_kafka
      dockerfile: Dockerfile
    networks:
      - kafka-net
    ports:
      - 3006:3000
    depends_on:
      - rabbitmq-mgmt

  rabbitmq-mgmt :
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672 
      - 15672:15672
    hostname: rabbit

  ampq_setup:
    build:
      context: ./esd_AMQP
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq-mgmt
